# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'CarShare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarShare

  pod 'SwiftLint'

  target 'CarShareTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
