// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: carshare_messaging.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// This is treated as a bitfield so we can set multiple permissions in one integer.
/// Packed into a fixed 32 bit type instead of varint encoding as we'll often set the high bits.
/// Beyond 32 permissions, we have to start a new enum type and permissions field.
enum PermissionFlags: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case permissionsNone // = 0
  case lock // = 1
  case unlockDriver // = 2
  case unlockAll // = 4
  case openTrunk // = 8
  case closeTrunk // = 16
  case locate // = 32
  case immobilize // = 64
  case mobilize // = 128
  case panicAlarmOn // = 256
  case panicAlarmOff // = 512
  case checkin // = 1024
  case checkout // = 2048
  case connect // = 4096
  case disconnect // = 8192
  case observe // = 16384
  case createReservation // = 32768
  case readReservation // = 65536
  case modifyReservation // = 131072
  case deleteReservation // = 262144
  case serviceModeRequest // = 524288
  case blacklistUser // = 1048576
  case remoteStart // = 2097152
  case secureConditionsCheck // = 4194304
  case UNRECOGNIZED(Int)

  init() {
    self = .permissionsNone
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .permissionsNone
    case 1: self = .lock
    case 2: self = .unlockDriver
    case 4: self = .unlockAll
    case 8: self = .openTrunk
    case 16: self = .closeTrunk
    case 32: self = .locate
    case 64: self = .immobilize
    case 128: self = .mobilize
    case 256: self = .panicAlarmOn
    case 512: self = .panicAlarmOff
    case 1024: self = .checkin
    case 2048: self = .checkout
    case 4096: self = .connect
    case 8192: self = .disconnect
    case 16384: self = .observe
    case 32768: self = .createReservation
    case 65536: self = .readReservation
    case 131072: self = .modifyReservation
    case 262144: self = .deleteReservation
    case 524288: self = .serviceModeRequest
    case 1048576: self = .blacklistUser
    case 2097152: self = .remoteStart
    case 4194304: self = .secureConditionsCheck
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .permissionsNone: return 0
    case .lock: return 1
    case .unlockDriver: return 2
    case .unlockAll: return 4
    case .openTrunk: return 8
    case .closeTrunk: return 16
    case .locate: return 32
    case .immobilize: return 64
    case .mobilize: return 128
    case .panicAlarmOn: return 256
    case .panicAlarmOff: return 512
    case .checkin: return 1024
    case .checkout: return 2048
    case .connect: return 4096
    case .disconnect: return 8192
    case .observe: return 16384
    case .createReservation: return 32768
    case .readReservation: return 65536
    case .modifyReservation: return 131072
    case .deleteReservation: return 262144
    case .serviceModeRequest: return 524288
    case .blacklistUser: return 1048576
    case .remoteStart: return 2097152
    case .secureConditionsCheck: return 4194304
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension PermissionFlags: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [PermissionFlags] = [
    .permissionsNone,
    .lock,
    .unlockDriver,
    .unlockAll,
    .openTrunk,
    .closeTrunk,
    .locate,
    .immobilize,
    .mobilize,
    .panicAlarmOn,
    .panicAlarmOff,
    .checkin,
    .checkout,
    .connect,
    .disconnect,
    .observe,
    .createReservation,
    .readReservation,
    .modifyReservation,
    .deleteReservation,
    .serviceModeRequest,
    .blacklistUser,
    .remoteStart,
    .secureConditionsCheck,
  ]
}

#endif  // swift(>=4.2)

enum VehicleSecureConditionsFlags: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case secureConditionNone // = 0
  case windowsUp // = 1
  case sunroofClosed // = 2
  case convertibleClosed // = 4
  case doorsClosed // = 8
  case ignitionOff // = 16
  case lightsOff // = 32
  case UNRECOGNIZED(Int)

  init() {
    self = .secureConditionNone
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .secureConditionNone
    case 1: self = .windowsUp
    case 2: self = .sunroofClosed
    case 4: self = .convertibleClosed
    case 8: self = .doorsClosed
    case 16: self = .ignitionOff
    case 32: self = .lightsOff
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .secureConditionNone: return 0
    case .windowsUp: return 1
    case .sunroofClosed: return 2
    case .convertibleClosed: return 4
    case .doorsClosed: return 8
    case .ignitionOff: return 16
    case .lightsOff: return 32
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension VehicleSecureConditionsFlags: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [VehicleSecureConditionsFlags] = [
    .secureConditionNone,
    .windowsUp,
    .sunroofClosed,
    .convertibleClosed,
    .doorsClosed,
    .ignitionOff,
    .lightsOff,
  ]
}

#endif  // swift(>=4.2)

/// This is the root message of the carshare messaging specification.
/// All protobug messages sent / received via BT-IOX for carshare are contained here.
/// Serialization/deserialization is always to/from this message.
struct AppToDeviceMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: AppToDeviceMessage.OneOf_Message? = nil

  var command: DeviceCommandMessage {
    get {
      if case .command(let v)? = message {return v}
      return DeviceCommandMessage()
    }
    set {message = .command(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Message: Equatable {
    case command(DeviceCommandMessage)

  #if !swift(>=4.1)
    static func ==(lhs: AppToDeviceMessage.OneOf_Message, rhs: AppToDeviceMessage.OneOf_Message) -> Bool {
      switch (lhs, rhs) {
      case (.command(let l), .command(let r)): return l == r
      }
    }
  #endif
  }

  init() {}
}

struct DeviceToAppMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: DeviceToAppMessage.OneOf_Message? = nil

  /// TODO: add context to this message 
  var result: ResultMessage {
    get {
      if case .result(let v)? = message {return v}
      return ResultMessage()
    }
    set {message = .result(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Message: Equatable {
    /// TODO: add context to this message 
    case result(ResultMessage)

  #if !swift(>=4.1)
    static func ==(lhs: DeviceToAppMessage.OneOf_Message, rhs: DeviceToAppMessage.OneOf_Message) -> Bool {
      switch (lhs, rhs) {
      case (.result(let l), .result(let r)): return l == r
      }
    }
  #endif
  }

  init() {}
}

struct ReservationStateSyncMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var reservations: [DeviceReservationMessage] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// For communication from Car Share framework to Go devices
struct DeviceCommandMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var command: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum Command: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case noCommand // = 0
    case lock // = 1
    case unlockDriver // = 2
    case unlockAll // = 4
    case openTrunk // = 8
    case closeTrunk // = 16
    case locate // = 32
    case immobilize // = 64
    case mobilize // = 128
    case checkin // = 1024
    case checkout // = 2048
    case secureConditionsCheck // = 4194304
    case UNRECOGNIZED(Int)

    init() {
      self = .noCommand
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .noCommand
      case 1: self = .lock
      case 2: self = .unlockDriver
      case 4: self = .unlockAll
      case 8: self = .openTrunk
      case 16: self = .closeTrunk
      case 32: self = .locate
      case 64: self = .immobilize
      case 128: self = .mobilize
      case 1024: self = .checkin
      case 2048: self = .checkout
      case 4194304: self = .secureConditionsCheck
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .noCommand: return 0
      case .lock: return 1
      case .unlockDriver: return 2
      case .unlockAll: return 4
      case .openTrunk: return 8
      case .closeTrunk: return 16
      case .locate: return 32
      case .immobilize: return 64
      case .mobilize: return 128
      case .checkin: return 1024
      case .checkout: return 2048
      case .secureConditionsCheck: return 4194304
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}
}

#if swift(>=4.2)

extension DeviceCommandMessage.Command: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [DeviceCommandMessage.Command] = [
    .noCommand,
    .lock,
    .unlockDriver,
    .unlockAll,
    .openTrunk,
    .closeTrunk,
    .locate,
    .immobilize,
    .mobilize,
    .checkin,
    .checkout,
    .secureConditionsCheck,
  ]
}

#endif  // swift(>=4.2)

/// Toggles for modifying the permissions of a booking
struct ReservationPrivilegeToggles {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var privilegeField: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum Privilege: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case noPrivileges // = 0
    case resetAtEndOfBooking // = 1
    case checkinOverride // = 2
    case ignoreCheckoutFail // = 4
    case UNRECOGNIZED(Int)

    init() {
      self = .noPrivileges
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .noPrivileges
      case 1: self = .resetAtEndOfBooking
      case 2: self = .checkinOverride
      case 4: self = .ignoreCheckoutFail
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .noPrivileges: return 0
      case .resetAtEndOfBooking: return 1
      case .checkinOverride: return 2
      case .ignoreCheckoutFail: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}
}

#if swift(>=4.2)

extension ReservationPrivilegeToggles.Privilege: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [ReservationPrivilegeToggles.Privilege] = [
    .noPrivileges,
    .resetAtEndOfBooking,
    .checkinOverride,
    .ignoreCheckoutFail,
  ]
}

#endif  // swift(>=4.2)

struct StatusData {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: UInt32 = 0

  var value: UInt32 = 0

  var dateTimeMs: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// returned after challenge / response is complete
struct ResultMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var success: Bool = false

  var statusData: [StatusData] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct DeviceReservationMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// GO only supports a public exponent of 0x10001 so a modulus is enough to determine the public key
  var appPublicModulus: Data = SwiftProtobuf.Internal.emptyData

  var keyExpiry: UInt64 = 0

  var reservationID: String = String()

  var deviceHardwareID: UInt64 = 0

  var account: Account {
    get {return _account ?? Account()}
    set {_account = newValue}
  }
  /// Returns true if `account` has been explicitly set.
  var hasAccount: Bool {return self._account != nil}
  /// Clears the value of `account`. Subsequent reads from it will return its default value.
  mutating func clearAccount() {self._account = nil}

  /// Timestamp represented by seconds since Unix Epoch
  var reservationStartTime: UInt64 = 0

  /// Timestamp represented by seconds since Unix Epoch
  var reservationEndTime: UInt64 = 0

  var gracePeriodSeconds: UInt32 = 0

  var securePeriodSeconds: UInt32 = 0

  var endBookConditions: EndBookConditions {
    get {return _endBookConditions ?? EndBookConditions()}
    set {_endBookConditions = newValue}
  }
  /// Returns true if `endBookConditions` has been explicitly set.
  var hasEndBookConditions: Bool {return self._endBookConditions != nil}
  /// Clears the value of `endBookConditions`. Subsequent reads from it will return its default value.
  mutating func clearEndBookConditions() {self._endBookConditions = nil}

  var proxCardID: UInt32 = 0

  var reservationPrivileges: ReservationPrivilegeToggles {
    get {return _reservationPrivileges ?? ReservationPrivilegeToggles()}
    set {_reservationPrivileges = newValue}
  }
  /// Returns true if `reservationPrivileges` has been explicitly set.
  var hasReservationPrivileges: Bool {return self._reservationPrivileges != nil}
  /// Clears the value of `reservationPrivileges`. Subsequent reads from it will return its default value.
  mutating func clearReservationPrivileges() {self._reservationPrivileges = nil}

  var deviceSerialNo: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _account: Account? = nil
  fileprivate var _endBookConditions: EndBookConditions? = nil
  fileprivate var _reservationPrivileges: ReservationPrivilegeToggles? = nil
}

struct Account {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  /// enum Permission
  var permissions: PermissionList {
    get {return _permissions ?? PermissionList()}
    set {_permissions = newValue}
  }
  /// Returns true if `permissions` has been explicitly set.
  var hasPermissions: Bool {return self._permissions != nil}
  /// Clears the value of `permissions`. Subsequent reads from it will return its default value.
  mutating func clearPermissions() {self._permissions = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _permissions: PermissionList? = nil
}

/// Eventually we may have more than one permissions bitfield to send, this message encapsulates
/// all permissions bitfields (transmitted as 32-bit integers) in a single message.
struct PermissionList {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// enum PermissionFlags
  var permissions: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct EndBookConditions {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var vehicleSecureConditions: VehicleSecureConditions {
    get {return _vehicleSecureConditions ?? VehicleSecureConditions()}
    set {_vehicleSecureConditions = newValue}
  }
  /// Returns true if `vehicleSecureConditions` has been explicitly set.
  var hasVehicleSecureConditions: Bool {return self._vehicleSecureConditions != nil}
  /// Clears the value of `vehicleSecureConditions`. Subsequent reads from it will return its default value.
  mutating func clearVehicleSecureConditions() {self._vehicleSecureConditions = nil}

  var homePoint: GpsCoordinate {
    get {return _homePoint ?? GpsCoordinate()}
    set {_homePoint = newValue}
  }
  /// Returns true if `homePoint` has been explicitly set.
  var hasHomePoint: Bool {return self._homePoint != nil}
  /// Clears the value of `homePoint`. Subsequent reads from it will return its default value.
  mutating func clearHomePoint() {self._homePoint = nil}

  var homeRadius: UInt32 = 0

  var fuelTankGreaterThan: Float = 0

  var conditions: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum Conditions: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case endBookNone // = 0
    case endBookIgnitionOff // = 1
    case endBookHomePoint // = 2
    case endBookFuelLevel // = 4
    case UNRECOGNIZED(Int)

    init() {
      self = .endBookNone
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .endBookNone
      case 1: self = .endBookIgnitionOff
      case 2: self = .endBookHomePoint
      case 4: self = .endBookFuelLevel
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .endBookNone: return 0
      case .endBookIgnitionOff: return 1
      case .endBookHomePoint: return 2
      case .endBookFuelLevel: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}

  fileprivate var _vehicleSecureConditions: VehicleSecureConditions? = nil
  fileprivate var _homePoint: GpsCoordinate? = nil
}

#if swift(>=4.2)

extension EndBookConditions.Conditions: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [EndBookConditions.Conditions] = [
    .endBookNone,
    .endBookIgnitionOff,
    .endBookHomePoint,
    .endBookFuelLevel,
  ]
}

#endif  // swift(>=4.2)

struct VehicleSecureConditions {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// enum VehicleSecureConditionsFlags
  var vehicleSecureConditions: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct GpsCoordinate {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var latitude: Float = 0

  var longitude: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

///*
/// Carshare Public Key Message
/// Generated in the Carshare Service, consumed by the Go device.
struct CarsharePublicKeyMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Timestamp represented by seconds since Unix Epoch
  var rotationTimestamp: UInt64 = 0

  /// An empty byte string on this property indicates that there is no active public key for the device 
  var publicModulus1: Data = SwiftProtobuf.Internal.emptyData

  var publicModulus2: Data = SwiftProtobuf.Internal.emptyData

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension PermissionFlags: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "PERMISSIONS_NONE"),
    1: .same(proto: "LOCK"),
    2: .same(proto: "UNLOCK_DRIVER"),
    4: .same(proto: "UNLOCK_ALL"),
    8: .same(proto: "OPEN_TRUNK"),
    16: .same(proto: "CLOSE_TRUNK"),
    32: .same(proto: "LOCATE"),
    64: .same(proto: "IMMOBILIZE"),
    128: .same(proto: "MOBILIZE"),
    256: .same(proto: "PANIC_ALARM_ON"),
    512: .same(proto: "PANIC_ALARM_OFF"),
    1024: .same(proto: "CHECKIN"),
    2048: .same(proto: "CHECKOUT"),
    4096: .same(proto: "CONNECT"),
    8192: .same(proto: "DISCONNECT"),
    16384: .same(proto: "OBSERVE"),
    32768: .same(proto: "CREATE_RESERVATION"),
    65536: .same(proto: "READ_RESERVATION"),
    131072: .same(proto: "MODIFY_RESERVATION"),
    262144: .same(proto: "DELETE_RESERVATION"),
    524288: .same(proto: "SERVICE_MODE_REQUEST"),
    1048576: .same(proto: "BLACKLIST_USER"),
    2097152: .same(proto: "REMOTE_START"),
    4194304: .same(proto: "SECURE_CONDITIONS_CHECK"),
  ]
}

extension VehicleSecureConditionsFlags: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SECURE_CONDITION_NONE"),
    1: .same(proto: "WINDOWS_UP"),
    2: .same(proto: "SUNROOF_CLOSED"),
    4: .same(proto: "CONVERTIBLE_CLOSED"),
    8: .same(proto: "DOORS_CLOSED"),
    16: .same(proto: "IGNITION_OFF"),
    32: .same(proto: "LIGHTS_OFF"),
  ]
}

extension AppToDeviceMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AppToDeviceMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "command"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1:
        var v: DeviceCommandMessage?
        if let current = self.message {
          try decoder.handleConflictingOneOf()
          if case .command(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {self.message = .command(v)}
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if case .command(let v)? = self.message {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: AppToDeviceMessage, rhs: AppToDeviceMessage) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DeviceToAppMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "DeviceToAppMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "result"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1:
        var v: ResultMessage?
        if let current = self.message {
          try decoder.handleConflictingOneOf()
          if case .result(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {self.message = .result(v)}
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if case .result(let v)? = self.message {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DeviceToAppMessage, rhs: DeviceToAppMessage) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ReservationStateSyncMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ReservationStateSyncMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "reservations"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.reservations)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.reservations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.reservations, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ReservationStateSyncMessage, rhs: ReservationStateSyncMessage) -> Bool {
    if lhs.reservations != rhs.reservations {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DeviceCommandMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "DeviceCommandMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "command"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularFixed32Field(value: &self.command)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.command != 0 {
      try visitor.visitSingularFixed32Field(value: self.command, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DeviceCommandMessage, rhs: DeviceCommandMessage) -> Bool {
    if lhs.command != rhs.command {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DeviceCommandMessage.Command: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NO_COMMAND"),
    1: .same(proto: "LOCK"),
    2: .same(proto: "UNLOCK_DRIVER"),
    4: .same(proto: "UNLOCK_ALL"),
    8: .same(proto: "OPEN_TRUNK"),
    16: .same(proto: "CLOSE_TRUNK"),
    32: .same(proto: "LOCATE"),
    64: .same(proto: "IMMOBILIZE"),
    128: .same(proto: "MOBILIZE"),
    1024: .same(proto: "CHECKIN"),
    2048: .same(proto: "CHECKOUT"),
    4194304: .same(proto: "SECURE_CONDITIONS_CHECK"),
  ]
}

extension ReservationPrivilegeToggles: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ReservationPrivilegeToggles"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "privilege_field"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularFixed32Field(value: &self.privilegeField)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.privilegeField != 0 {
      try visitor.visitSingularFixed32Field(value: self.privilegeField, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ReservationPrivilegeToggles, rhs: ReservationPrivilegeToggles) -> Bool {
    if lhs.privilegeField != rhs.privilegeField {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ReservationPrivilegeToggles.Privilege: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NO_PRIVILEGES"),
    1: .same(proto: "RESET_AT_END_OF_BOOKING"),
    2: .same(proto: "CHECKIN_OVERRIDE"),
    4: .same(proto: "IGNORE_CHECKOUT_FAIL"),
  ]
}

extension StatusData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "StatusData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "value"),
    3: .standard(proto: "date_time_ms"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt32Field(value: &self.id)
      case 2: try decoder.decodeSingularUInt32Field(value: &self.value)
      case 3: try decoder.decodeSingularUInt64Field(value: &self.dateTimeMs)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularUInt32Field(value: self.id, fieldNumber: 1)
    }
    if self.value != 0 {
      try visitor.visitSingularUInt32Field(value: self.value, fieldNumber: 2)
    }
    if self.dateTimeMs != 0 {
      try visitor.visitSingularUInt64Field(value: self.dateTimeMs, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: StatusData, rhs: StatusData) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.value != rhs.value {return false}
    if lhs.dateTimeMs != rhs.dateTimeMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ResultMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ResultMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "success"),
    2: .standard(proto: "status_data"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularBoolField(value: &self.success)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.statusData)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.statusData.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.statusData, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ResultMessage, rhs: ResultMessage) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.statusData != rhs.statusData {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DeviceReservationMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "DeviceReservationMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "app_public_modulus"),
    2: .standard(proto: "key_expiry"),
    3: .standard(proto: "reservation_id"),
    4: .standard(proto: "device_hardware_id"),
    5: .same(proto: "account"),
    6: .standard(proto: "reservation_start_time"),
    7: .standard(proto: "reservation_end_time"),
    8: .standard(proto: "grace_period_seconds"),
    9: .standard(proto: "secure_period_seconds"),
    10: .standard(proto: "end_book_conditions"),
    11: .standard(proto: "prox_card_id"),
    12: .standard(proto: "reservation_privileges"),
    13: .standard(proto: "device_serial_no"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularBytesField(value: &self.appPublicModulus)
      case 2: try decoder.decodeSingularUInt64Field(value: &self.keyExpiry)
      case 3: try decoder.decodeSingularStringField(value: &self.reservationID)
      case 4: try decoder.decodeSingularUInt64Field(value: &self.deviceHardwareID)
      case 5: try decoder.decodeSingularMessageField(value: &self._account)
      case 6: try decoder.decodeSingularUInt64Field(value: &self.reservationStartTime)
      case 7: try decoder.decodeSingularUInt64Field(value: &self.reservationEndTime)
      case 8: try decoder.decodeSingularUInt32Field(value: &self.gracePeriodSeconds)
      case 9: try decoder.decodeSingularUInt32Field(value: &self.securePeriodSeconds)
      case 10: try decoder.decodeSingularMessageField(value: &self._endBookConditions)
      case 11: try decoder.decodeSingularUInt32Field(value: &self.proxCardID)
      case 12: try decoder.decodeSingularMessageField(value: &self._reservationPrivileges)
      case 13: try decoder.decodeSingularStringField(value: &self.deviceSerialNo)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.appPublicModulus.isEmpty {
      try visitor.visitSingularBytesField(value: self.appPublicModulus, fieldNumber: 1)
    }
    if self.keyExpiry != 0 {
      try visitor.visitSingularUInt64Field(value: self.keyExpiry, fieldNumber: 2)
    }
    if !self.reservationID.isEmpty {
      try visitor.visitSingularStringField(value: self.reservationID, fieldNumber: 3)
    }
    if self.deviceHardwareID != 0 {
      try visitor.visitSingularUInt64Field(value: self.deviceHardwareID, fieldNumber: 4)
    }
    if let v = self._account {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }
    if self.reservationStartTime != 0 {
      try visitor.visitSingularUInt64Field(value: self.reservationStartTime, fieldNumber: 6)
    }
    if self.reservationEndTime != 0 {
      try visitor.visitSingularUInt64Field(value: self.reservationEndTime, fieldNumber: 7)
    }
    if self.gracePeriodSeconds != 0 {
      try visitor.visitSingularUInt32Field(value: self.gracePeriodSeconds, fieldNumber: 8)
    }
    if self.securePeriodSeconds != 0 {
      try visitor.visitSingularUInt32Field(value: self.securePeriodSeconds, fieldNumber: 9)
    }
    if let v = self._endBookConditions {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }
    if self.proxCardID != 0 {
      try visitor.visitSingularUInt32Field(value: self.proxCardID, fieldNumber: 11)
    }
    if let v = self._reservationPrivileges {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }
    if !self.deviceSerialNo.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceSerialNo, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DeviceReservationMessage, rhs: DeviceReservationMessage) -> Bool {
    if lhs.appPublicModulus != rhs.appPublicModulus {return false}
    if lhs.keyExpiry != rhs.keyExpiry {return false}
    if lhs.reservationID != rhs.reservationID {return false}
    if lhs.deviceHardwareID != rhs.deviceHardwareID {return false}
    if lhs._account != rhs._account {return false}
    if lhs.reservationStartTime != rhs.reservationStartTime {return false}
    if lhs.reservationEndTime != rhs.reservationEndTime {return false}
    if lhs.gracePeriodSeconds != rhs.gracePeriodSeconds {return false}
    if lhs.securePeriodSeconds != rhs.securePeriodSeconds {return false}
    if lhs._endBookConditions != rhs._endBookConditions {return false}
    if lhs.proxCardID != rhs.proxCardID {return false}
    if lhs._reservationPrivileges != rhs._reservationPrivileges {return false}
    if lhs.deviceSerialNo != rhs.deviceSerialNo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Account: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Account"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "permissions"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularMessageField(value: &self._permissions)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if let v = self._permissions {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Account, rhs: Account) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs._permissions != rhs._permissions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PermissionList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PermissionList"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "permissions"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularFixed32Field(value: &self.permissions)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.permissions != 0 {
      try visitor.visitSingularFixed32Field(value: self.permissions, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PermissionList, rhs: PermissionList) -> Bool {
    if lhs.permissions != rhs.permissions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension EndBookConditions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "EndBookConditions"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "vehicle_secure_conditions"),
    2: .standard(proto: "home_point"),
    3: .standard(proto: "home_radius"),
    4: .standard(proto: "fuel_tank_greater_than"),
    5: .same(proto: "conditions"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._vehicleSecureConditions)
      case 2: try decoder.decodeSingularMessageField(value: &self._homePoint)
      case 3: try decoder.decodeSingularUInt32Field(value: &self.homeRadius)
      case 4: try decoder.decodeSingularFloatField(value: &self.fuelTankGreaterThan)
      case 5: try decoder.decodeSingularFixed32Field(value: &self.conditions)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._vehicleSecureConditions {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if let v = self._homePoint {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    if self.homeRadius != 0 {
      try visitor.visitSingularUInt32Field(value: self.homeRadius, fieldNumber: 3)
    }
    if self.fuelTankGreaterThan != 0 {
      try visitor.visitSingularFloatField(value: self.fuelTankGreaterThan, fieldNumber: 4)
    }
    if self.conditions != 0 {
      try visitor.visitSingularFixed32Field(value: self.conditions, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: EndBookConditions, rhs: EndBookConditions) -> Bool {
    if lhs._vehicleSecureConditions != rhs._vehicleSecureConditions {return false}
    if lhs._homePoint != rhs._homePoint {return false}
    if lhs.homeRadius != rhs.homeRadius {return false}
    if lhs.fuelTankGreaterThan != rhs.fuelTankGreaterThan {return false}
    if lhs.conditions != rhs.conditions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension EndBookConditions.Conditions: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "END_BOOK_NONE"),
    1: .same(proto: "END_BOOK_IGNITION_OFF"),
    2: .same(proto: "END_BOOK_HOME_POINT"),
    4: .same(proto: "END_BOOK_FUEL_LEVEL"),
  ]
}

extension VehicleSecureConditions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "VehicleSecureConditions"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "vehicle_secure_conditions"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularFixed32Field(value: &self.vehicleSecureConditions)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.vehicleSecureConditions != 0 {
      try visitor.visitSingularFixed32Field(value: self.vehicleSecureConditions, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: VehicleSecureConditions, rhs: VehicleSecureConditions) -> Bool {
    if lhs.vehicleSecureConditions != rhs.vehicleSecureConditions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension GpsCoordinate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "GpsCoordinate"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "latitude"),
    2: .same(proto: "longitude"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularFloatField(value: &self.latitude)
      case 2: try decoder.decodeSingularFloatField(value: &self.longitude)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.latitude != 0 {
      try visitor.visitSingularFloatField(value: self.latitude, fieldNumber: 1)
    }
    if self.longitude != 0 {
      try visitor.visitSingularFloatField(value: self.longitude, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GpsCoordinate, rhs: GpsCoordinate) -> Bool {
    if lhs.latitude != rhs.latitude {return false}
    if lhs.longitude != rhs.longitude {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CarsharePublicKeyMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "CarsharePublicKeyMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "rotation_timestamp"),
    2: .standard(proto: "public_modulus_1"),
    3: .standard(proto: "public_modulus_2"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt64Field(value: &self.rotationTimestamp)
      case 2: try decoder.decodeSingularBytesField(value: &self.publicModulus1)
      case 3: try decoder.decodeSingularBytesField(value: &self.publicModulus2)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.rotationTimestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.rotationTimestamp, fieldNumber: 1)
    }
    if !self.publicModulus1.isEmpty {
      try visitor.visitSingularBytesField(value: self.publicModulus1, fieldNumber: 2)
    }
    if !self.publicModulus2.isEmpty {
      try visitor.visitSingularBytesField(value: self.publicModulus2, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CarsharePublicKeyMessage, rhs: CarsharePublicKeyMessage) -> Bool {
    if lhs.rotationTimestamp != rhs.rotationTimestamp {return false}
    if lhs.publicModulus1 != rhs.publicModulus1 {return false}
    if lhs.publicModulus2 != rhs.publicModulus2 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
